version: '3.8'

services:
  blofin-proxy:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DEBUG=true
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
